import { IoMdHome } from 'react-icons/io';
import {
  TbArrowLeft,
  TbArrowRight,
  TbBan,
  TbBeach,
  TbCalendarMonth,
  TbCheck,
  TbChevronDown,
  TbChevronLeft,
  TbChevronRight,
  TbClipboardCheck,
  TbClock,
  TbClockEdit,
  TbCoffee,
  TbFileCertificate,
  TbFirstAidKit,
  TbLogin2,
  TbLogout2,
  TbPencil,
  TbPlayerPlay,
  TbPlus,
  TbReport,
  TbUpload,
  TbUserCircle,
  TbUserPlus,
  TbUsers,
  TbX,
} from 'react-icons/tb';

export { appIcons };

// The icons of the app: the Tabler icons of react-icons, in the current text color.
const appIcons = {
  app: <TbClock size={22} aria-hidden />,
  home: <IoMdHome size={18} aria-hidden />,
  chevronDown: <TbChevronDown size={16} aria-hidden />,
  previous: <TbChevronLeft size={16} aria-hidden />,
  next: <TbChevronRight size={16} aria-hidden />,
  back: <TbArrowLeft size={18} aria-hidden />,
  forward: <TbArrowRight size={18} aria-hidden />,
  open: <TbArrowRight size={16} aria-hidden />,
  target: <TbArrowRight size={12} aria-hidden />,
  // The modules.
  clock: <TbClock size={18} aria-hidden />,
  timesheet: <TbReport size={18} aria-hidden />,
  leave: <TbBeach size={18} aria-hidden />,
  sick: <TbFirstAidKit size={18} aria-hidden />,
  calendar: <TbCalendarMonth size={18} aria-hidden />,
  employees: <TbUsers size={18} aria-hidden />,
  approvals: <TbClipboardCheck size={18} aria-hidden />,
  // The actions.
  clockIn: <TbLogin2 size={18} aria-hidden />,
  clockOut: <TbLogout2 size={18} aria-hidden />,
  breakStart: <TbCoffee size={18} aria-hidden />,
  breakEnd: <TbPlayerPlay size={18} aria-hidden />,
  add: <TbPlus size={16} aria-hidden />,
  addEmployee: <TbUserPlus size={16} aria-hidden />,
  edit: <TbPencil size={16} aria-hidden />,
  correction: <TbClockEdit size={16} aria-hidden />,
  approve: <TbCheck size={16} aria-hidden />,
  reject: <TbX size={16} aria-hidden />,
  cancel: <TbBan size={16} aria-hidden />,
  upload: <TbUpload size={16} aria-hidden />,
  certificate: <TbFileCertificate size={16} aria-hidden />,
  user: <TbUserCircle size={18} aria-hidden />,
};
