import { defineUseForm } from './defineUseForm';
import { catalogs, type LibCatalog, type MessageKey } from './messages';
import { binding, formMeta, formRegistry } from './meta';
import type {
  Binding,
  BindingConfig,
  FieldArg,
  FieldFn,
  FieldOptions,
  FieldProps,
  Fields,
  FormConfig,
  FormMeta,
  FormProps,
  I18nAdapter,
  I18nConfig,
  Message,
  MessageCatalog,
  MessageContext,
  MessageFn,
  PluralForms,
  PropNames,
  SubmitContext,
  SubmitOutcome,
  SubmitResult,
  UseFormOptions,
  UseFormReturn,
  ValidateOn,
} from './types';

export { binding, catalogs, defineUseForm, formMeta, formRegistry };
export type {
  Binding,
  BindingConfig,
  FieldArg,
  FieldFn,
  FieldOptions,
  FieldProps,
  Fields,
  FormConfig,
  FormMeta,
  FormProps,
  I18nAdapter,
  I18nConfig,
  LibCatalog,
  Message,
  MessageCatalog,
  MessageContext,
  MessageFn,
  MessageKey,
  PluralForms,
  PropNames,
  SubmitContext,
  SubmitOutcome,
  SubmitResult,
  UseFormOptions,
  UseFormReturn,
  ValidateOn,
};
