import { IoMdHome } from 'react-icons/io';
import {
  TbArrowLeft,
  TbArrowRight,
  TbArrowsRightLeft,
  TbBriefcase,
  TbCake,
  TbCash,
  TbCheck,
  TbChecklist,
  TbChevronDown,
  TbConfetti,
  TbDoorEnter,
  TbDoorExit,
  TbDots,
  TbDownload,
  TbFileText,
  TbHierarchy2,
  TbMail,
  TbMapPin,
  TbPencil,
  TbPhone,
  TbPlus,
  TbSitemap,
  TbStar,
  TbStarFilled,
  TbTrash,
  TbTrendingUp,
  TbUpload,
  TbUserCheck,
  TbUserCircle,
  TbUserPlus,
  TbUsers,
  TbUsersGroup,
  TbX,
} from 'react-icons/tb';

export { appIcons };

// The icons of the app: the Tabler icons of react-icons, in the current text color.
const appIcons = {
  app: <TbUsersGroup size={22} aria-hidden />,
  home: <IoMdHome size={18} aria-hidden />,
  chevronDown: <TbChevronDown size={16} aria-hidden />,
  back: <TbArrowLeft size={18} aria-hidden />,
  forward: <TbArrowRight size={18} aria-hidden />,
  open: <TbArrowRight size={16} aria-hidden />,
  target: <TbArrowRight size={12} aria-hidden />,
  more: <TbDots size={16} aria-hidden />,
  // The modules.
  employees: <TbUsers size={18} aria-hidden />,
  departments: <TbSitemap size={18} aria-hidden />,
  recruiting: <TbBriefcase size={18} aria-hidden />,
  checklists: <TbChecklist size={18} aria-hidden />,
  // The tabs of an employee.
  salary: <TbCash size={16} aria-hidden />,
  documents: <TbFileText size={16} aria-hidden />,
  orgChart: <TbHierarchy2 size={16} aria-hidden />,
  // The actions.
  add: <TbPlus size={16} aria-hidden />,
  addEmployee: <TbUserPlus size={16} aria-hidden />,
  edit: <TbPencil size={16} aria-hidden />,
  remove: <TbTrash size={16} aria-hidden />,
  upload: <TbUpload size={16} aria-hidden />,
  download: <TbDownload size={16} aria-hidden />,
  raise: <TbTrendingUp size={16} aria-hidden />,
  move: <TbArrowsRightLeft size={16} aria-hidden />,
  hire: <TbUserCheck size={16} aria-hidden />,
  reject: <TbX size={16} aria-hidden />,
  check: <TbCheck size={16} aria-hidden />,
  onboarding: <TbDoorEnter size={16} aria-hidden />,
  offboarding: <TbDoorExit size={16} aria-hidden />,
  user: <TbUserCircle size={18} aria-hidden />,
  // The details and the events.
  mail: <TbMail size={14} aria-hidden />,
  phone: <TbPhone size={14} aria-hidden />,
  location: <TbMapPin size={14} aria-hidden />,
  birthday: <TbCake size={16} aria-hidden />,
  anniversary: <TbConfetti size={16} aria-hidden />,
  star: <TbStar size={13} aria-hidden />,
  starFilled: <TbStarFilled size={13} aria-hidden />,
};
